
INSERT INTO OSC.OSC_PARAMETER_CONFIG VALUES('FLAG', 'flag.enoti', 'Y');
--ECAS
INSERT INTO OSC.OSC_PARAMETER_CONFIG VALUES('ECAS', 'eventNotificationPolicyIdEN', '1M1R_CONFIRM_CODE_TH');
INSERT INTO OSC.OSC_PARAMETER_CONFIG VALUES('ECAS', 'eventNotificationPolicyIdTH', '1M1R_CONFIRM_CODE_TH');
INSERT INTO OSC.OSC_PARAMETER_CONFIG VALUES('ECAS', 'tokenPolicyId', '1M1R_OTP');
INSERT INTO OSC.OSC_PARAMETER_CONFIG VALUES('ECAS', 'storeId', 'MemoryTokenStore');
INSERT INTO OSC.OSC_PARAMETER_CONFIG VALUES('ECAS', 'bankRef', '1MB');
INSERT INTO OSC.OSC_PARAMETER_CONFIG VALUES('ECAS', 'smsSubjectEN', '1M1R_CONFIRM_CODE_TH');
INSERT INTO OSC.OSC_PARAMETER_CONFIG VALUES('ECAS', 'smsSubjectTH', '1M1R_CONFIRM_CODE_TH');
INSERT INTO OSC.OSC_PARAMETER_CONFIG VALUES('ECAS', 'productCode', 'OTH-1MB');
INSERT INTO OSC.OSC_PARAMETER_CONFIG VALUES('ECAS', 'channel', 'OneScreen');

INSERT INTO OSC.OSC_PARAMETER_CONFIG VALUES('ECAS', 'mbf_eventNotificationPolicyIdEN', 'BEN_OTP_EN');
INSERT INTO OSC.OSC_PARAMETER_CONFIG VALUES('ECAS', 'mbf_eventNotificationPolicyIdTH', 'BEN_OTP_TH');
INSERT INTO OSC.OSC_PARAMETER_CONFIG VALUES('ECAS', 'mbf_tokenPolicyId', 'BEN_OTP');
INSERT INTO OSC.OSC_PARAMETER_CONFIG VALUES('ECAS', 'mbf_storeId', 'MemoryTokenStore');
INSERT INTO OSC.OSC_PARAMETER_CONFIG VALUES('ECAS', 'mbf_bankRef', 'OTH1BEN');
INSERT INTO OSC.OSC_PARAMETER_CONFIG VALUES('ECAS', 'mbf_smsSubjectEN', 'BEN_OTP_TH');
INSERT INTO OSC.OSC_PARAMETER_CONFIG VALUES('ECAS', 'mbf_smsSubjectTH', 'BEN_OTP_TH');
INSERT INTO OSC.OSC_PARAMETER_CONFIG VALUES('ECAS', 'mbf_productCode', 'OTH1BEN');
INSERT INTO OSC.OSC_PARAMETER_CONFIG VALUES('ECAS', 'mbf_channel', 'OneScreen');

--ETE
INSERT INTO OSC.OSC_PARAMETER_CONFIG VALUES('PDPA', 'OSC_API_KEY', 'MTFsWEo0VTh6MVlXRjR4NkwxbDBLNDYzSg==');
