
--create backup table
CREATE TABLE OSC.MAIN_PROD_CODE_BK LIKE OSC.MAIN_PROD_CODE;
INSERT INTO OSC.MAIN_PROD_CODE_BK (SELECT * FROM OSC.MAIN_PROD_CODE);

--drop master table
DROP TABLE OSC.MAIN_PROD_CODE;

--create empty master table
CREATE TABLE OSC.MAIN_PROD_CODE LIKE OSC.MAIN_PROD_CODE_BK;
--------------------------

--create backup table
CREATE TABLE OSC.MAIN_FEE_BK LIKE OSC.MAIN_FEE;
INSERT INTO OSC.MAIN_FEE_BK (SELECT * FROM OSC.MAIN_FEE);

--drop master table
DROP TABLE OSC.MAIN_FEE;

--create empty master table
CREATE TABLE OSC.MAIN_FEE LIKE OSC.MAIN_FEE_BK;
--------------------------

--create backup table
CREATE TABLE OSC.OSC_EFORM_BK LIKE OSC.OSC_EFORM;
INSERT INTO OSC.OSC_EFORM_BK (SELECT * FROM OSC.OSC_EFORM);

--drop master table
DROP TABLE OSC.OSC_EFORM;

--create empty master table
CREATE TABLE OSC.OSC_EFORM LIKE OSC.OSC_EFORM_BK;
--------------------------

--create backup table
CREATE TABLE OSC.OSC_EFORM_GROUP_BK LIKE OSC.OSC_EFORM_GROUP;
INSERT INTO OSC.OSC_EFORM_GROUP_BK (SELECT * FROM OSC.OSC_EFORM_GROUP);

--drop master table
DROP TABLE OSC.OSC_EFORM_GROUP;

--create empty master table
CREATE TABLE OSC.OSC_EFORM_GROUP LIKE OSC.OSC_EFORM_GROUP_BK;
--------------------------

--create backup table
CREATE TABLE OSC.OSC_EFORM_MAPPING_BK LIKE OSC.OSC_EFORM_MAPPING;
INSERT INTO OSC.OSC_EFORM_MAPPING_BK (SELECT * FROM OSC.OSC_EFORM_MAPPING);

--drop master table
DROP TABLE OSC.OSC_EFORM_MAPPING;

--create empty master table
CREATE TABLE OSC.OSC_EFORM_MAPPING LIKE OSC.OSC_EFORM_MAPPING_BK;
--------------------------

--create backup table
CREATE TABLE OSC.OSC_SERVICE_ENDPOINT_BK LIKE OSC.OSC_SERVICE_ENDPOINT;
INSERT INTO OSC.OSC_SERVICE_ENDPOINT_BK (SELECT * FROM OSC.OSC_SERVICE_ENDPOINT);

--drop master table
DROP TABLE OSC.OSC_SERVICE_ENDPOINT;

--create empty master table
CREATE TABLE OSC.OSC_SERVICE_ENDPOINT LIKE OSC.OSC_SERVICE_ENDPOINT_BK;




